### ISSUE TITLE
Ran setup.sh, and 'Botnet' templates.  Doesn't connect to Binance..

### ISSUE THREAD

**Issue by brizzbane** [creslinux/freqcache#8]
Getting the error: 

> 
> template.TestStrategy.json_1  | 2021-02-20 21:48:01,405 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
> template.TestStrategy.json_1  | 2021-02-20 21:48:01,412 - freqtrade.exchange.exchange - WARNING - Unable to initialize markets. Reason: binance GET https://api.binance.com/api/v3/exchangeInfo
> template.TestStrategy.json_1  | 2021-02-20 21:48:01,413 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
> template.TestStrategy.json_1  | 2021-02-20 21:48:01,421 - freqtrade.exchange.exchange - WARNING - Unable to initialize markets. Reason: binance GET https://api.binance.com/api/v3/exchangeInfo
> template.TestStrategy.json_1  | 2021-02-20 21:48:01,421 - freqtrade.resolvers.exchange_resolver - INFO - No Binance specific subclass found. Using the generic class instead.
> template.TestStrategy.json_1  | 2021-02-20 21:48:01,421 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
> template.TestStrategy.json_1  | 2021-02-20 21:48:01,421 - freqtrade.exchange.exchange - INFO - Using CCXT 1.40.99
> template.TestStrategy.json_1  | 2021-02-20 21:48:01,439 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
> template.TestStrategy.json_1  | 2021-02-20 21:48:01,443 - freqtrade.exchange.exchange - WARNING - Unable to initialize markets. Reason: binance GET https://api.binance.com/api/v3/exchangeInfo
> template.TestStrategy.json_1  | 2021-02-20 21:48:01,443 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
> template.TestStrategy.json_1  | 2021-02-20 21:48:01,447 - freqtrade.exchange.exchange - WARNING - Unable to initialize markets. Reason: binance GET https://api.binance.com/api/v3/exchangeInfo
> template.TestStrategy.json_1  | 2021-02-20 21:48:01,447 - freqtrade.commands.trade_commands - ERROR - 'NoneType' object has no attribute 'items'
> template.TestStrategy.json_1  | 2021-02-20 21:48:01,447 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
> template.TestStrategy.json_1  | Traceback (most recent call last):
> template.TestStrategy.json_1  |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
> template.TestStrategy.json_1  |     worker = Worker(args)
> template.TestStrategy.json_1  |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
> template.TestStrategy.json_1  |     self._init(False)
> template.TestStrategy.json_1  |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
> template.TestStrategy.json_1  |     self.freqtrade = FreqtradeBot(self._config)
> template.TestStrategy.json_1  |   File "/freqtrade/freqtrade/freqtradebot.py", line 71, in __init__
> template.TestStrategy.json_1  |     self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
> template.TestStrategy.json_1  |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 38, in load_exchange
> template.TestStrategy.json_1  |     exchange = Exchange(config, validate=validate)
> template.TestStrategy.json_1  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 127, in __init__
> template.TestStrategy.json_1  |     self.validate_stakecurrency(config['stake_currency'])
> template.TestStrategy.json_1  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 322, in validate_stakecurrency
> template.TestStrategy.json_1  |     quote_currencies = self.get_quote_currencies()
> template.TestStrategy.json_1  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 238, in get_quote_currencies
> template.TestStrategy.json_1  |     return sorted(set([x['quote'] for _, x in markets.items()]))
> template.TestStrategy.json_1  | AttributeError: 'NoneType' object has no attribute 'items'

I'm guessing this means that it can't connect to the binance api.  I went to the URL manually (since project hasn't been updated in a while)--and the URL is still valid.

Would love if you could comment about any insights as to what my issue might be.

Trying to debug myself,if I comment out the dns entry (dns: 10.99.7.249) it DOES connect/work.  But I think that the whole point is to go through the dns?

**Comment by brizzbane** [comment]
More info:

> ft_dnsmasq      | dnsmasq: query[A] api.binance.com from 10.99.0.2
> ft_dnsmasq      | dnsmasq: config api.binance.com is 10.99.7.251
> ft_hitch        | 20210221T194950.366894 [    9] 10.99.0.2:34214 :0 7:8 proxy connect
> ft_hitch        | 20210221T194950.366915 [    9] 10.99.0.2:34214 :0 7:8 ssl handshake start
> ft_hitch        | 20210221T194950.366942 [    9] 10.99.0.2:34214 :0 7:8 ssl client handshake revents=1
> ft_hitch        | 20210221T194950.367352 [    9] 10.99.0.2:34214 :0 7:8 ssl client handshake err=SSL_ERROR_WANT_READ
> ft_hitch        | 20210221T194950.367469 [    9] 10.99.0.2:34214 :0 7:8 ssl client handshake revents=1
> ft_hitch        | 20210221T194950.367497 [    9] 10.99.0.2:34214 :0 7:8 ssl client handshake err=SSL_ERROR_SSL
> ft_hitch        | 20210221T194950.367514 [    9] 10.99.0.2:34214 :0 7:8 Handshake failure: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate
> ft_hitch        | 20210221T194950.367531 [    9] 10.99.0.2:34214 :0 7:8 proxy shutdown req=SHUTDOWN_SSL
> ft_hitch        | 20210221T194950.367544 [    9] 10.99.0.2:34214 :0 7:8 proxy shutdown req=SHUTDOWN_HARD
> 

@berlinguyinca Hey ;).  I think original author might be MIA..  Was just wondering if you might have any idea?  I've been messing with this and have no idea.  Have tried updating Hitch thinking maybe SSL would be fixed, but that hasn't worked.

It looks like the author was in contact with you.  Were you able to get it running?  Did you run into this error?  I have tried with other sites like "kraken", and "bittrex", both have same hangup with hitch.

If you can provide any insight or direction that would be awesome!  Really looking to get something setup to help w/API cache.

**Comment by berlinguyinca** [comment]
This has been long left behind and is no further being developed.

**Comment by brizzbane** [comment]
Yea, kind of got that.   Isn't the idea behind it still relevant though?  I started looking into this more after going live, and having errors of 'DDOS' IP backoff protection errors from Freqtrade, running only one bot.

Right now I'm looking into just using varnish.  I guess I'm still wondering what your thoughts are about the project though.  Is idea behind caching requests to API still revelant?

**Comment by berlinguyinca** [comment]
I'm personally using an nginx proxy and wrote my own bot due to the issues
with freqtrade and lack of scalability

**Comment by brizzbane** [comment]
Yea...I've even thought about doing something similar, looking into using Zipline and https://github.com/bmoscon/cryptofeed.

*really* appreciate your feedback and insight.

**Comment by berlinguyinca** [comment]
Well it took about 3 years to write a working bot. So you will be in for
the long run. And that's really before strategies. Still working on better
strategies.

**Comment by brizzbane** [comment]
Yea..I was thinking to myself when working with Freqtrade--so glad all I have to worry about is the strategies.

If you are up for sharing anything, I... I don't know.  Figure I might as well ask.  I can work on it full time.  If you have any interest in working something out :\.

**Comment by berlinguyinca** [comment]
Sadly not at liberty to share it at this stage.
